/**
 * Created by amira on 6/8/15.
 */
import _ from 'lodash';
import {listen, Report} from '../testDrivers/gopostalRecorder';

export default function (chai) {

	/**
	 * matches a report that is generated by the function under test
	 */
	chai.Assertion.addMethod("report", function reportImpl({context, level, params}) {
		var predicate = (r) => (!context || r.context === context) && (!level || r.level === level) && (!params || ~r.params.indexOf(params) || params.every(p => ~r.params.indexOf(p)));
		this.assert(listen(this._obj).some(predicate),
			`Expected report to be included in gopostal reports, but it wasn't.`,
			`Expected report not to be included in gopostal reports, but it was.`
		);
	});

}