/**
 * Created by amira on 6/8/15.
 */
import _ from 'lodash';
import {listen, Report} from '../testDrivers/gopostalRecorder';

export default function (chai) {

	/**
	 * matches a report that is generated by the function under test
	 * Matching logic is similar to
	 * https://lodash.com/docs#some
	 */
	chai.Assertion.addMethod("report", function (predicate, thisarg) {
		this.assert(_.some(listen(this._obj), predicate, thisarg),
			`Expected report to be included in gopostal reports, but it wasn't.`,
			`Expected report not to be included in gopostal reports, but it was.`
		);	});

}